# Generated by Django 5.2.4 on 2025-08-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.JSONField()),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('prime', models.BooleanField(default=False)),
                ('certified', models.BooleanField(default=False)),
                ('os', models.CharField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, null=True)),
                ('modal', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, null=True)),
                ('sellertype', models.CharField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, null=True)),
                ('charge', models.CharField(blank=True, null=True)),
                ('label', models.CharField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, null=True)),
                ('color', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('cprice', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
